apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup-zitadel-ams
  namespace: identity
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: zitadel
