---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager-base
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/dagobah/certmanager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager-conf
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: certmanager-base
  path: ./infra/dagobah/certmanager/conf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
