apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs
  namespace: juicefs
spec:
  interval: 2h
  chart:
    spec:
      chart: juicefs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: juicefs-charts 
        namespace: flux-system
      interval: 2h
  values:
    node:
      terminationGracePeriodSeconds: 60
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
  juicefs/mount-delete-delay: 1m
  juicefs/clean-cache: "true"
