apiVersion: v1
kind: Secret
metadata:
    name: jfs-ams
    type: Opaque
stringData:
    name: ENC[AES256_GCM,data:JQ/DN1KCtrWDsQ5kkQzj,iv:XM7uQhMb/2jreiUWaUXCzAmMv6+pQ0fUOVWAK0lOpKc=,tag:QrWFOIacvcxWFjNjDIaKbg==,type:str]
    metaurl: ENC[AES256_GCM,data:iVQsVTbN9hEfruPgJaKVR1oel15QQmmbggalLDl4hBhSLIexU9fs6hNCIvGMYmd0GCHXMSp2T3PWusJZfWLHTG8Lygvigzx29M9ep1jtLfUDnLdA0VHNtOZLNgrcmCjJMYoSTuWXzeuwAik=,iv:oj2hYWOVJ7mDTzEcfPNIabjWmGx+Tn9d9k5NVKK7nbw=,tag:1SAk2dkMTpNG7m920VA6Ug==,type:str]
    storage: ENC[AES256_GCM,data:4Kk=,iv:LvLbKQ0G1/vWyGFneKZv8orV8DUifXvGJn2CG0hXPik=,tag:d46h9GerXJnj8zkziXdK+Q==,type:str]
    bucket: ENC[AES256_GCM,data:KwQADyoAUksIrew+md1h0KJRpNm676Df/iK45TpS1ZIDhUoflxzG9UtzAxlXsiXxUHOqnXBjY8K3APzb35JtSkkhw8L59lWWV4PPO6lv,iv:25uJT328bLLfa8/3di4OiuONjW5W6tzmwwRZ88Q5c9U=,tag:1RVe9gBu30XgKQvxcmklKA==,type:str]
    access-key: ENC[AES256_GCM,data:cTMnVvb++F11Likk5tpR8OWFOgF0KIz/lzJfAZ08gX0=,iv:BXsV6V+mAsAwY+q4UWCpGWhz0iFRVDcOnvJpm9TWB2M=,tag:NbLUERpdakAcA45VvAotmg==,type:str]
    secret-key: ENC[AES256_GCM,data:BcVFAWarEICqRPAJahqydUea862eGy8uPr2pMDdzj/E=,iv:QytHFMin1ppAftGVy4/rzlrYo/u+g0YtW1R4zOCm47g=,tag:iEK9r5YJJZ3qmMDNyX7InA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-05T10:13:20Z"
    mac: ENC[AES256_GCM,data:RtfU55Z4ouu5MpjUC7xZZXxxBnjozUIrg93Lw9bC+cOQu5vvhq9FGK65Ek2hWzme2GiNdShXo5vCQat9hVDqXfi2wgoVFuF2Yiy0stJgfkSz9PC+1W8wqAxzdxcd+v5jPdpUvzK9UegQS1zvBT+0C5CC4SCucJyT8B+rLPx5CSM=,iv:Y66WpGWTeoMWpmd81ZBdkvUB5aRUl4WUfZNnCuKA1nw=,tag:nLReq2hdQPDxoqqFUbrU1w==,type:str]
    pgp:
        - created_at: "2024-08-10T12:21:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ejCwjtN08KAQ/9FHFeQCZytvgu1Qm+0GRmzgViLxQkGsYrN4mY1srzXMHT
            xYAEixXRRPyZSu5G+Ev2vqiaS6OLm6b7D0lj2Q2+tWYqM155MXdM2Val1jQD7wKr
            D7XzVH+GQBh5wIdiFF+prBnBKmLZLIus2OlDaWS6ky1KcBuk5JUMqEk93NR2rEh4
            Z+4dWFvI2g2OLhZ9y+nQP8qOuVzdqsRMz/ndj2fgAfy89a9lA/mr99Lqv3Zox7k0
            G4oPKgJ6g+aA0qcBCEtMKbffDdk0j8E9JXUSaKcP+h+q9IO0+l4lZBdvYaE/mrGM
            8IwiUfZ7NxAClVwezI20KHwIyLgfFwARsawHdq3PzDHWws9GEqdyulx8E9H2rfdw
            xGXUMRr1WeBTIt/LJjz9XCONZUmrgL8SVuyF67s14n1nhMrddye1/HtOihI0NH0a
            Ok5QLC1IjhVdfLuy9y+ykJAxF2oNWUUInNP2Vkw+Q83pzr/Ux9+LD504w/9lEi/m
            Ex/39RFJQQzhD3IGDdM9t0ViVYwhZEiN2wGuWupMnMqytvPEGYeOKQ4ENyU9A5OU
            ueSl/dRhvhi8jPCr4Gx0KWNDslinoYIfu0u1uckG9qeN+/b4zZ3/ramEK6up8wB0
            qvUK4GRfo8CKn1+XsEinvmRfkx6bAi4IX9q6p50TlOy8/g5w4vYHSgElAaAaXkbU
            aAEJAhC6iEVUhc/6sT4ONJoqKpIOdjhNHoQOC1Du3Dk93o9HsFjG6R3DYttvZFzR
            3toB12pMd4yeH62WZw72BxTMv6paP0nC2bZgrPITJdEfNSV0YxnP8O0/ZRgL4+sa
            I4cCVTdxJN+Z
            =9yrF
            -----END PGP MESSAGE-----
          fp: 03FC3E1D8797BBD9C275804D0CEF33994271303E
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
