apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
resources:
- ../cloudnative-pg/pg-gitea-user.yaml
patches:
- target:
    kind: Secret
    name: pg-gitea-user
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: gitea
