apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - ../shared
  - ../cloudnative-pg/pg-superuser.yaml
  - ../cloudnative-pg/pg-s3-credentials.yaml
  - ../cloudnative-pg/pg-vaultwarden-user.yaml
