apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
- ../cloudnative-pg/pg-vaultwarden-user.yaml
patches:
- target:
    kind: Secret
    name: pg-vaultwarden-user
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: vaultwarden
