apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 60m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      version: 4.10.1
  dependsOn:
  - name: cert-manager
    namespace: ingress
  interval: 60m
  values:
    controller:
      allowSnippetAnnotations: true
      replicaCount: 2
      service:
        type: LoadBalancer
        externalTrafficPolicy: "Local"
        loadBalancerIP: 127.0.0.1
        annotations:
          loadbalancer.openstack.org/hostname: "example.com"
          loadbalancer.openstack.org/proxy-protocol: "true"
          loadbalancer.openstack.org/keep-floatingip: "true"
      config:
        use-proxy-protocol: true
        proxy-buffer-size: 16k