apiVersion: v1
data:
    password: ENC[AES256_GCM,data:FGA4tY7trWGCbdwGxf38fWpCT5Q19uh+fB7ooeiU/tY=,iv:8g2AA+Vhx/ogIL3c81KKjJhumFpzFnWQVB2PGeHJs1s=,tag:8SvK+IyUAr4T4Fsz1VSuhQ==,type:str]
    username: ENC[AES256_GCM,data:/M0VahOjQz1vq77Mr5d0yA==,iv:O7T00ygeN4eYlIICCk8ZycKVANz5qPLX9TILKnWPuiM=,tag:hcniZwCpIcv0IvpuQ390Ng==,type:str]
kind: Secret
metadata:
    name: pg-vaultwarden-user
    namespace: databases
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-01T17:15:01Z"
    mac: ENC[AES256_GCM,data:wPMT2hgyV+xBlLoTWse/k7qoO30/iYPnb8molp8ASxlUIATIi+NSRj6KKak4m+0hgqG1gnxVZWcV0R64WxjCMNr/D00yWv7KYP9Q/zb8MU93j5G7X/586RBQ7fLjwKk0WhXClw7ldETcoFrWRybY/aJHnj5/OfF6gPfi2Tgq78w=,iv:HGlsTHg8HAeiZkZ+iyvvMsQr7kJstWj6ChaHmygm3ok=,tag:OJiEWfXJoL/GLKHXHeeKnw==,type:str]
    pgp:
        - created_at: "2024-06-01T17:15:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ejCwjtN08KARAAhQJ6cY1c512SeBsZy6hrgPeULeFtDV+H29MQJwnCNSag
            nCbld6mPkXrgBG0R7qT3Cp4rmM8n8RQHiwgOrAdSLZjMNOHZIJGjakWlQ0sWfY7H
            aK2BWdMOaBJnSB5L9Xbf2ADF1J7fVUHmeBfmNiCyNVriQlohO+pbMi8WbZ8zBffE
            fInCePwZWUeArhUtbZq1XfIy8PVUgnj2uXEt+sw/9qt2SexW7Su4wnWG95eVdVX1
            3sVn5VDAkD0JmwH1TBScgQyAAF5FkQvz3bq7JkaQh1DDkHGeBx32Z+6yXUra2taJ
            NBidPCQaCZeuzsycecZiaRX6RlFDXTKuGb+A81N5e3voxNTssAESDFmtuFqtsEz0
            m1ulZMcFjdoPiyOpCyjWmWtsl1euOIudz7Ai58/FAXjSuWsIRFzqTAjb6TwAqAtv
            x47VecCgWtketQSRgnFAjph2647ysNspsp3rRUSuuQtcGjRdlTwdZDStGCt4WZsr
            f4y9GP5CKpVYgN7sumhtJEKR+GA+6jKKFzmb1HK5v/y+DeIiEBgefK4mEWG896mN
            R5SO4oylxURM9u5Yt/XRq6hszatiLKUbGEb6toV6mfcccN0wozJgPyK+YJu900+T
            Ml0B/bh0Xtv7A/TtPBVRVX6Foh+5vkGY2RgmlG3+N3IWBiBqwAvUfdqC5hTohO/U
            aAEJAhD8xk8sK1X6Tot/OVT4gBZUwIqN+8pNaw3MmjfXQjfFkaKVvC//vYr4LMmQ
            g4gy/LTeAdQDTRym72VNvYQ4crQyBhUH7D60w02LqYejLwU9ilgmheKzxkxKUXNc
            EUxI6YaP/hFL
            =9JdK
            -----END PGP MESSAGE-----
          fp: 03FC3E1D8797BBD9C275804D0CEF33994271303E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
