apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 60m
  url: https://guerzon.github.io/vaultwarden
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden/vaultwarden
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: vaultwarden
      version: 0.22.7
  interval: 60m
  values:
    domain: "https://vault.dagobah.txit.me/"
    database:
      type: postgresql
      existingSecret: "database-uri"
      existingSecretKey: "secret-uri"
    ingress:
      enabled: true
      class: "nginx"
      tlsSecret: wildcard-dagobah-txit-me-tls
      hostname: vault.dagobah.txit.me
    adminToken:
      value: $$argon2id$$v=19$$m=19456,t=2,p=1$$djFIRkRBVzJaOFg0cTFIVzZBZmc1NGJwQVJIUGo1aWQrSjZJV2VJZnhMMD0$$BDmSpH3LlBDnEA/BpaSGuOu7FQS2oQ0nmLXpKp+2b7E
    data:
      name: "vaultwarden-data"
      size: "5Gi"
      class: "default"
      keepPvc: true
