apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bjw-s.yaml
  - juicefs.yaml
patches:
  - path: common.yaml
    target:
      kind: HelmRepository
