apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["samtoxie/flux-txit","samtoxie/tatooine-applications"],
      "platform": "github",
      "autodiscover": false,
      "flux": {
        "fileMatch": ["\\.yaml$"]
      },
      "docker-compose": {
        "fileMatch": ["(^|\/)(?:docker-)?compose[^\/]*\.ya?ml(\.j2|)$"]
      }
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: '0,20,40 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: renovate/renovate:38.43.0
            name: renovate-bot
            env:
            - name: RENOVATE_BASE_DIR
              value: '/tmp/renovate/'
            - name: RENOVATE_CONFIG_FILE
              value: '/opt/renovate/config.json'
            - name: LOG_LEVEL
              value: info
            envFrom:
            - secretRef:
                name: renovate-env
            volumeMounts:
            - name: config-volume
              mountPath: /opt/renovate/
            - name: work-volume
              mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
          - name: config-volume
            configMap:
              name: renovate-config
          - name: work-volume
            emptyDir: {}
