---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: jfs-ams
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
  csi.storage.k8s.io/provisioner-secret-name: jfs-ams
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
  juicefs/mount-delete-delay: 1m
  juicefs/clean-cache: "true"
