apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
  namespace: gitea
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  description: Postgresql cluster for gitea
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-19
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: default
  bootstrap:
    # initdb: {}
    recovery:
      source: gitea
    # recovery:
    #   backup:
    #     name: daily-backup-vaultwarden-20240516000000
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 764Mi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
  monitoring:
    enablePodMonitor: false
  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      destinationPath: s3://dagobah-backups/cnpg
      endpointURL: https://core.fuga.cloud:8080
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: s3-ams
          key: access-key-id
        secretAccessKey:
          name: s3-ams
          key: secret-access-key
  externalClusters:
    - name: gitea
      barmanObjectStore:
        destinationPath: s3://dagobah-backups/cnpg
        endpointURL: https://core.fuga.cloud:8080
        wal:
          compression: bzip2
          maxParallel: 8
        s3Credentials:
          accessKeyId:
            name: s3-ams
            key: access-key-id
          secretAccessKey:
            name: s3-ams
            key: secret-access-key
