apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.1/8
            - 192.168.0.1/16
        proxyProtocol:
          trustedIPs:
            - 10.0.0.1/8
            - 192.168.0.1/16
      websecure:
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.1/8
            - 192.168.0.1/16
        proxyProtocol:
          trustedIPs:
            - 10.0.0.1/8
            - 192.168.0.1/16
    service:
      spec:
        externalTrafficPolicy: Local