apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-dagobah-txit-me-tls
  namespace: ingress
spec:
  dnsNames:
  - '*.dagobah.txit.me'
  - 'dagobah.txit.me'
  secretName: wildcard-dagobah-txit-me-tls
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
    group: cert-manager.io
