apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup-gitea
  namespace: gitea
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: gitea
