apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup-vaultwarden
  namespace: vaultwarden
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: vaultwarden
