apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden
  namespace: databases
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  description: Postgresql cluster for vaultwarden
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-19
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: default
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-superuser
  bootstrap:
    # initdb:
    #   database: vaultwarden
    #   owner: vaultwarden
    #   secret:
    #   name: pg-vaultwarden-user
    recovery:
      source: vaultwarden
    # recovery:
    #   backup:
    #     name: daily-backup-vaultwarden-20240516000000
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 764Mi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://dagobah-backups/cnpg
      endpointURL: https://fra.fuga.cloud:8080
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: pg-s3-credentials
          key: access-key-id
        secretAccessKey:
          name: pg-s3-credentials
          key: secret-access-key
  externalClusters:
  - name: vaultwarden
    barmanObjectStore:
      destinationPath: s3://dagobah-backups/cnpg
      endpointURL: https://fra.fuga.cloud:8080
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: pg-s3-credentials
          key: access-key-id
        secretAccessKey:
          name: pg-s3-credentials
          key: secret-access-key
