apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-config-v1
  namespace: netbird
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default