apiVersion: v1
kind: Secret
metadata:
    name: routing-peer-secret
    namespace: netbird
stringData:
    setup-key: ENC[AES256_GCM,data:flY1qHFgTcoVTrmG2Ez89FMxE2Yue3w/yj8/5aBl9hktoek/,iv:ZzGKq7lC4iCMvNeA5TBvATQX4+CA15VtHQIQ6O8auPA=,tag:ZSCe/2tgOdV2v4PNI1ymtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-07T08:09:30Z"
    mac: ENC[AES256_GCM,data:sUEYYkVKAE9DQAbvertAo81qhKMRbVf6o/OIMjVl75jzeUtPSNBMkabD1MkBlUBAmS7tmsx2SCvgN9/0dcbvv3OeMswDMiCi5IB892QsQqB+goGK7k/Sllg3q90G1MT8CHq635NmPVD2Ea1XiDNHI3RkrTKpkFgEOj0wA7IMK5I=,iv:3kdScrXGkdnXZUOLLBMIcMwNzX1p8H6sYLFo+c0UWRQ=,tag:eeErySZZflsODcIcOP2UCg==,type:str]
    pgp:
        - created_at: "2025-01-06T21:18:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ejCwjtN08KAQ//YUzkWz+KqBKj4FVITrKuDY5HzQkJZ9nVB/YLLE7qQH7M
            VODalxsznFdocRGA5HwOXM1IN2RQbObmclfhpKLS+GHaH6xKGCDKxTYUneegoceq
            G8vODxR5ebN3Eq/gwiqYDJRZJPvpmUhGgDv2pfzQupDp6wTO4cFz7HJF7Z4kkBKK
            6lWXrdxZ0uPtc8Pg93jaEi2OPRBzoHPXMIqZegpmFQj/ZMIGQ97VSPHDy8aX3o1T
            4i8Y9ULOZceow1If/xbO6Lt2XVGJeqQRzCK+G7icUbFIQquoV42cKRsVy3euc0Un
            0U9Ea6o/+MdIVEjeI4d2wj7u1lGdDdIBGOJlSbcOj628bgutxuFvIJaluYcZrR62
            0AgFZnak3JBx4aoec8YZ0ffYOoxO1R04jYT9CWk5tyn9qirgBwM6imbdz+gmAJyE
            E7rnVw6F7Wa4yheUE1CCygjh0r0UCniDxiFl+YnXXytmxZdBwyVNA7Jr4K8szCMN
            QHgyyeT4c30ZTU6o76ERv2V88E3LCVZKXuwMxJ/7SBoSVOpov9h6nMpIxChoug7r
            H2JiShuFgxbfTw/y+t7ojr1+Y4QkfEJiGPsfLF+QJE+0y+AaB/9X3m1dH7vj1pVp
            janmnn5hIi4OW59WM5mqJ7Cr9YCEvOLJnp8YaBWKfqscGwG4WtW/DHwIPUV4lM/U
            aAEJAhDsul7xEJl3q2hdfaKn0JJkwsk/UShlcGF41bd6lxgnHZFGA+g4APlFpp4b
            BHvDRpW9brgPfHNTw3tyzIfxepMs46hV3VF9KLf48KzGTj90DbZ0EEcN1jrLp+6L
            wWM7bnvGApG2
            =FT5R
            -----END PGP MESSAGE-----
          fp: 03FC3E1D8797BBD9C275804D0CEF33994271303E
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
