apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup-netbird
  namespace: netbird
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: pg-netbird-new