apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:OAQpy4bJ1R9Xbl666MB91WpQQpe+EuNapaBlZ9IImqp/rJuSvNyM8A==,iv:ZTWQjl2Cvbxk0VQqeazaHD7FAWjQvDQp2t+Uz9OKYr4=,tag:MZvC/2S1OXJA2b4z29DkWg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-08-12T08:45:40Z"
  mac: ENC[AES256_GCM,data:fbIuyYzzv2H9xQfaY7bFGLlELU5MEHNqXrjml0kBcslH0C+QeEza0Xk7O901J/dEcPfsPeVDf6LMkkV+ei7grCstNiosyR+6pt1lBeBr1izICLsbfix+APyhZhNlgc6ec15dfroZIhHyHccXIeZSNE6xNqRzntWX/a7l6ng5g1k=,iv:EB+KiqOUnIlNOcGvMUp9lTxeJKvY48NPL55n/L673ts=,tag:JSfsw2jWrV/ASxQnRL6n4A==,type:str]
  pgp:
  - created_at: "2024-08-12T08:45:40Z"
    enc: |-
      -----BEGIN PGP MESSAGE-----

      hQIMA/ejCwjtN08KAQ//StyM8jP8+pRTKcouWW2W74fCMvlxzydSlwzJVu4VRRdB
      Ii8ugM9P7wCdoJAycn5/yvi4gNSAmkFaoHsbGXFPhcW2tzkTU2ZXHyZYgl4Q3l+T
      Sckp+UhhprxaS8ew3JOmwIs0NmvoHI0l/xi5XubUAG0DbDO7KpUVk8JwI2QeD2Dp
      tfLsOT6GvSyL+Oz13hayL2o2Vc0234ggnkmT5eR0dCskMBkGs2UgXNYPPq2FENSx
      r4/YmYQdyInWNj4SwzFvls+veBf+6Dbdo837Q0jbROdBII2EAWcR9+3ujHZUNfDV
      ZwFyBkLnxqOj04kMx+TEYUXYNHzg4M/7Efani5iiNp07pIgEd+hxp3UlShb1FK7n
      c4XBNr15VrGK6edoIjnKG3fDIgfgX3OVsRtv8SCbvDpbMpNI7LyJTh814iX/vG+q
      Pwu1XeM+WT/xkpExebYApsKpwAQM5ov7XyBACtczPyRmjxWmygxUzKPDhNZzOsGa
      c6xdHYWWOA5fb29n/Va1+7HRrXoul+bJuygW5NNswvmB/jzZbtP99ceLXGz4P1VB
      8ijZJ/vsZlOh6GXgugzoBqwvUYa8s94IPgOFPq4RUhkmm5PQN4bhPjxi3zeyEAh6
      XLsdtTMlppFTpeg8xhcdgt5DnCsnFGYwiGlpJFd6PgwLMmmskVQuhEteJEwb7w3U
      aAEJAhBqp4MyrC4rDobekc21c1FAio81zDbDlIC6JzLR2UerBA/OvAH3Oiikfixu
      T076fr/TEd3hUempLXFHv2YaNEXvBhNB/pDutDd8fyKYUDlImnavKlZ0PTiYW5p+
      8JQXEFS9Sq3y
      =kwzD
      -----END PGP MESSAGE-----
    fp: 03FC3E1D8797BBD9C275804D0CEF33994271303E
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
