# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  values:
    controllers:
      vaultwarden:
        containers:
          app:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.32.4@sha256:7271b8ceb729f9b46144c800125813dcc8d16bb6874217c48e59b22b45e47d7d
            env:
              SIGNUPS_ALLOWED: false
              WEBSOCKET_ENABLED: true
              DOMAIN: https://vault.dagobah.txit.me
              DATABASE_URL:
                secretKeyRef:
                  name: vaultwarden-app
                  key: uri
              SMTP_HOST: smtppro.zoho.com
              SMTP_PORT: 587
              SMTP_SECURITY: starttls
              SMTP_FROM: info@toxopeus.it
              SMTP_USERNAME: sam@toxopeus.it
              SMTP_PASSWORD:
                secretKeyRef:
                  name: smtp
                  key: password
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
        statefulset:
          podManagementPolicy: Parallel
          volumeClaimTemplates:
            - accessMode: ReadWriteOnce
              globalMounts:
                - path: /data
              name: data
              size: 1Mi
        type: statefulset
    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
        hosts:
          - host: vault.dagobah.txit.me
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - vault.dagobah.txit.me
            secretName: vaultwarden-dns-tls
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: 80
