apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 120m
  chart:
    spec:
      chart: traefik
      version: "33.2.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 60m
  releaseName: traefik
  targetNamespace: traefik
  dependsOn:
  - name: cert-manager
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    rbac:
      enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
        ingressClass: traefik
      kubernetesGateway:
        enabled: false
    # gateway:
    #    listeners:
    #       websecure:
    #         port: 8443
    #         protocol: HTTPS
    #         namespacePolicy: All
    #         certificateRefs: 
    #           - name: wildcard-grombeer-pro-tls
    #             namespace: traefik
    globalArguments:
    - "--api.insecure=true"
    - "--serversTransport.insecureSkipVerify=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    additionalArguments:
    - --providers.kubernetesIngress.ingressEndpoint.publishedService=traefik/traefik
    - --entrypoints.websecure.forwardedHeaders.insecure
    - --entrypoints.web.forwardedHeaders.insecure
    - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
    - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
    - --entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,100.96.0.0/11,10.250.0.0/16,100.64.0.0/13
    - --entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,100.96.0.0/11,10.250.0.0/16,100.64.0.0/13
    service:
      annotations:
        loadbalancer.openstack.org/proxy-protocol: "true"
        loadbalancer.openstack.org/keep-floatingip: "true"
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: 81.24.6.164
    deployment:
      kind: Deployment
      replicas: 3
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        exposedPort: 443
        tls:
          enabled: true
          options: "default"
    logs:
      general:
        level: INFO
      access:
        enabled: true
    persistence:
      enabled: false
    podSecurityContext: null
    tls:
      options:
        default:
          cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
          curvePreferences:
          - CurveP521
          - CurveP384
          minVersion: VersionTLS12
          maxVersion: VersionTLS13
          sniStrict: true
