apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 120m
  chart:
    spec:
      chart: traefik
      version: "33.2.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 60m
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    rbac:
      enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowCrossNamespace: true
        ingressClass: traefik
      kubernetesGateway:
        enabled: false
    # gateway:
    #    listeners:
    #       websecure:
    #         port: 8443
    #         protocol: HTTPS
    #         namespacePolicy: All
    #         certificateRefs: 
    #           - name: wildcard-grombeer-pro-tls
    #             namespace: traefik
    globalArguments:
    - "--api.insecure=true"
    - "--serversTransport.insecureSkipVerify=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    additionalArguments:
    - --entrypoints.web.reusePort=true
    - --entrypoints.websecure.reusePort=true
    - --entrypoints.netbird.reusePort=true
    service:
      annotations:
        loadbalancer.openstack.org/proxy-protocol: "true"
        loadbalancer.openstack.org/keep-floatingip: "true"
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: 81.24.6.164
    deployment:
      kind: Deployment
      replicas: 3
    ports:
      web:
        redirectTo:
          port: websecure
        forwardedHeaders:
          trustedIPs:
          - 0.0.0.0/0
          insecure: true
        proxyProtocol:
          trustedIPs:
          - 0.0.0.0/0
          insecure: true
      websecure:
        exposedPort: 443
        forwardedHeaders:
          trustedIPs:
          - 0.0.0.0/0
          insecure: true
        proxyProtocol:
          trustedIPs:
          - 0.0.0.0/0
          insecure: true
        tls:
          enabled: true
          options: "default"
      netbird:
        port: 7443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        forwardedHeaders:
          trustedIPs:
          - 0.0.0.0/0
          insecure: true
        proxyProtocol:
          trustedIPs:
          - 0.0.0.0/0
          insecure: true
        transport:
          respondingTimeouts:
            readTimeout: 3600
            writeTimeout: 3600
            idleTimeout: 3600
          lifeCycle:
            requestAcceptGraceTimeout: 3600
            graceTimeOut: 3600
        tls:
          enabled: true
          options: "default"
    logs:
      general:
        level: INFO
      access:
        enabled: true
    persistence:
      enabled: false
    podSecurityContext: null
    tls:
      options:
        default:
          cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
          curvePreferences:
          - CurveP521
          - CurveP384
          minVersion: VersionTLS12
          maxVersion: VersionTLS13
          sniStrict: true
