apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 60m
  chart:
    spec:
      chart: traefik
      version: "33.2.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 60m
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    providers:
      kubernetesIngress:
        enabled: true
      kubernetesCRD:
        enabled: true
      kubernetesGateway:
        enabled: true
        experimentalChannel: true
    gateway:
      namespacePolicy: All
      # listeners:
      #   postgresql:
      #     port: 5432
      #     hostname: "*.cargobay-ams-1.txit.me"
      #     protocol: TLS
      #     namespacePolicy: All
      #     mode: Passthrough
    ports:
      # postgresql:
      #   port: 5432
      #   expose:
      #     default: true
      #   exposedPort: 5432
      #   protocol: TCP
      #   forwardedHeaders:
      #     trustedIPs:
      #       - 0.0.0.0/0
      #     insecure: true
      #   proxyProtocol:
      #     trustedIPs:
      #       - 0.0.0.0/0
      #     insecure: true
      web:
        forwardedHeaders:
          trustedIPs:
            - 0.0.0.0/0
          insecure: true
        proxyProtocol:
          trustedIPs:
            - 0.0.0.0/0
          insecure: true
      websecure:
        forwardedHeaders:
          trustedIPs:
            - 0.0.0.0/0
          insecure: true
        proxyProtocol:
          trustedIPs:
            - 0.0.0.0/0
          insecure: true
    service:
      annotations:
        loadbalancer.openstack.org/proxy-protocol: "true"
        loadbalancer.openstack.org/keep-floatingip: "true"
        # loadbalancer.openstack.org/hostname: "dummy.cargobay-ams-1.txit.me"
      spec:
        externalTrafficPolicy: Local
        # loadBalancerIP: 81.24.6.152
    metrics:
      prometheus:
        serviceMonitor:
          enabled: false
    logs:
      access:
        enabled: true
#    additionalArguments:
#      - --entrypoints.web.forwardedHeaders.insecure
#      - --entryPoints.web.proxyProtocol.trustedIPs=0.0.0.0/0
#      - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
#      - --entrypoints.websecure.forwardedHeaders.insecure
#      - --entryPoints.websecure.proxyProtocol.trustedIPs=0.0.0.0/0
#      - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
#      - --entrypoints.postgresql.forwardedHeaders.insecure
#      - --entryPoints.postgresql.proxyProtocol.trustedIPs=0.0.0.0/0
#      - --entryPoints.postgresql.forwardedHeaders.trustedIPs=0.0.0.0/0
