---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configs-dagobah
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/dagobah/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charts-dagobah
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: configs-dagobah
  path: ./clusters/dagobah/sources/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-dagobah
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: configs-dagobah
  path: ./secrets/dagobah
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-dagobah-applications
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: charts-dagobah
    - name: secrets-dagobah
  path: ./infra/dagobah/applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-dagobah-configs
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-dagobah-applications
  path: ./infra/dagobah/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dagobah
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: infra-dagobah-configs
  path: ./apps/dagobah
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
