---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-dagobah-applications
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: secrets-dagobah
  path: ./infra/dagobah/applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-dagobah-configs
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: infra-dagobah-applications
  path: ./infra/dagobah/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg