apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.10.1
  dependsOn:
    - name: cert-manager
      namespace: ingress
  interval: 60m
  values:
    controller:
      allowSnippetAnnotations: true
      replicaCount: 2
      service:
        type: LoadBalancer
        externalTrafficPolicy: "Local"
        loadBalancerIP: 81.24.6.77
        annotations:
          loadbalancer.openstack.org/hostname: "dagobah.txit.me"
          loadbalancer.openstack.org/proxy-protocol: "true"
          loadbalancer.openstack.org/keep-floatingip: "true"
      config:
        use-proxy-protocol: true
        proxy-buffer-size: 16k
