apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-http
  namespace: ingress
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: sam@toxopeus.it
    privateKeySecretRef:
      name: letsencrypt-staging-http
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-http
  namespace: ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sam@toxopeus.it
    privateKeySecretRef:
      name: letsencrypt-prod-http
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
  namespace: ingress
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sam@toxopeus.it
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
