apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
  namespace: databases
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  description: Postgresql cluster for Gitea
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-19
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: default
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-superuser
  bootstrap:
    # initdb:
    #   database: gitea
    #   owner: gitea
    #   secret:
    #     name: pg-gitea-user
    recovery:
      source: gitea
      # recovery:
      #   backup:
      #     name: daily-backup-gitea-20240516000000
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 764Mi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
  monitoring:
    enablePodMonitor: false
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://cluster-backups/cnpg
      endpointURL: https://fra.fuga.cloud:8080
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: pg-s3-credentials
          key: access-key-id
        secretAccessKey:
          name: pg-s3-credentials
          key: secret-access-key
  externalClusters:
  - name: gitea
    barmanObjectStore:
      destinationPath: s3://cluster-backups/cnpg
      endpointURL: https://fra.fuga.cloud:8080
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: pg-s3-credentials
          key: access-key-id
        secretAccessKey:
          name: pg-s3-credentials
          key: secret-access-key
