apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-predeploy
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/dagobah/netbird/predeploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
  #  - apiVersion: helm.toolkit.fluxcd.io/v2beta2
  #    kind: HelmRelease
  #    name: cargobay
  #    namespace: cargobay
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-deploy
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: netbird-predeploy
  path: ./apps/dagobah/netbird/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg