apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup-juicefs
  namespace: juicefs
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: juicefs
