apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: juicefs
  namespace: juicefs
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  description: Postgresql cluster for juicefs
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: default
  enableSuperuserAccess: true
  bootstrap:
    # initdb: {}
    recovery:
      source: juicefs
      recoveryTarget:
        targetTime: "2024-08-31 09:20:00.00000+02"
    # recovery:
    #   backup:
    #     name: daily-backup-vaultwarden-20240516000000
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 764Mi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
  monitoring:
    enablePodMonitor: false
  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      destinationPath: s3://dagobah-backups/cnpg
      endpointURL: https://fra.fuga.cloud:8080
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: s3-fra
          key: access-key-id
        secretAccessKey:
          name: s3-fra
          key: secret-access-key
  externalClusters:
    - name: juicefs
      barmanObjectStore:
        destinationPath: s3://dagobah-backups/cnpg
        endpointURL: https://fra.fuga.cloud:8080
        wal:
          compression: bzip2
          maxParallel: 8
        s3Credentials:
          accessKeyId:
            name: s3-fra
            key: access-key-id
          secretAccessKey:
            name: s3-fra
            key: secret-access-key
