---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: juicefs-base
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/venator/juicefs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: juicefs
      namespace: kube-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: juicefs-conf
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: juicefs-base
  path: ./infra/venator/juicefs/conf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
