apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:JZ7c4XlwoP57jMwRBFB6IZtTS0CrMWUG5YXomOnfBRYf6Lk2m5Ihl7eL+uE=,iv:4+0cvuHdcpqchce8+unUwAOqkx9CBiua6hWXnSyKaTE=,tag:wjPhFSpdp3hLMjpcK96b1Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:ptqextHayIz+YxIpCgJWWDuIj7PUq0HtkLXqEkfSlk9nI41drxGTz9Ym5U8=,iv:+rUz5FkWCjXI0VR6iNFOnr7Bs2qNOsLXO/HmdM0VydU=,tag:DmVscxEIfl1wtPzzFjS3ow==,type:str]
kind: Secret
metadata:
    name: s3-fra
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-10T12:05:52Z"
    mac: ENC[AES256_GCM,data:NT0p9nURQ1NjcTGeeeZpLE6+RAMj+S+g2bbGfY8+MzAau98smnCkthwQylW+GKTdHg0/jrYoAyfOSj//4wd8ISvEEtkbI6MkKIKmSFJUAGiYIsFZBtnFX+dZRX+19svdUBKKcOxmlGvenEr4xDCcUKZZdjMxXKLtab0AxiGJbzQ=,iv:tY6hhArkjqgY+Vp4iUo4kNOQaMXiZM1VPZ5ApMKLJN4=,tag:XKODdVflEntxljoej8osww==,type:str]
    pgp:
        - created_at: "2024-06-01T17:15:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/ejCwjtN08KAQ/7BZXMXpIVkekig1AHdL4U8ty3cKS3HGz8gYZryyhRqHea
            AsDP5Byq3mY7XpvzyoA74Eze6fM1vKAD8IZYUwxcfEqYtVXcT68cd2vyQ2SdQb2a
            czatTuo3TyH8nMy0Etb5lV4DUU9+iCbVPipaBhXkKNIzfiOu5jtDlUI/aq6+wwsP
            T0exG81SZBU82yk/tm05m9Geo06cIL/3hw9bbBQtYSx9r/VNAty9OF5S5hyYJAsT
            JhywfkOboqvxQapvZJko7HH2SfItiKOl4yL4q2+ca9mhpyuykvmrBjAJ0H3AvfxA
            HCYuGzfEZzWntvMxqodCuxecEI2rHHjZE+uDjknzKV8S3QPig3k58jMRpFVfYUma
            V9kmRqQ385F07rUGhUuPGdl5BW1WWrJ0YaUywmKHot/l24pS+wUjPXMy6R+bmOA1
            0+f9nEk7ugLV/fCUJIIgJUsfjicqI1gGBSS4V7pH90ZPAj1AXZtN56/KwkW+btQg
            y0AhGc48RQdN1XvNEAHqKhW8Z7ZX45KUM04Fsz61PWWeNJntnnPsaRTOektSb1AT
            BAtnujMTuXziV1BrVPLconaeeq+iBnUBvuHRg7aUVr2SXh33z1MQAVUyMHUvWqvp
            aUcOK5jic+UbJckPa6tmGFx4dKdkoGFIwoMAuZGkXxHTe3kiWPadAmib3CC9YqDU
            aAEJAhBmCEg4XO9xz++cgbp8j0LIEuGzd3RE/JwwbAW+/2bnryB/5OWOtVXp5QD6
            TdQHDuxs5i623b/cQo7k2UQ4CTyCOYT9RykwDjDuRNGc9Is3xFkA7boYYnPk/LGp
            44FbVFh6TGKI
            =nlwk
            -----END PGP MESSAGE-----
          fp: 03FC3E1D8797BBD9C275804D0CEF33994271303E
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
